alias gr='git remote'
alias gl="git log --pretty=format:\"%Creset%h : %cd [%cr] : %Cgreen%s %C(yellow)(%cn)%Creset\" --date=short"
alias lg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias up='git pull origin'
alias ga='git add'
alias gp='git push'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gk='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'
alias reset='git reset --hard'
alias clean='git clean -f -d'
alias reweb='git reset Lynda.Web.AuthorPortal.UI/Web.Config'
alias demo='git pull origin env_demo'
alias auth='git add Lynda.Web.AuthorPortal.UI/'
alias resethead='git reset --hard HEAD'
alias apply='git stash apply stash@{'
alias gc='clear'
alias gco='git gco'
alias wipe='git clean -f -d && git reset --hard'
alias new='git reset --hard && git clean -f -d && git fetch && git checkout -b get-926-nmhp-clean origin/env_stage'
home() { cd c:; cd repositories/Web; }
home